### ISSUE TITLE
Add substack link under "get in touch" section in homepage

### ISSUE THREAD

**Issue by emilio-silva** [ethereumba/EthereumBA-web#42]
Icon image: https://cdn.substack.com/image/fetch/c_limit,f_auto,q_auto:good/https%3A%2F%2Fsubstack.com%2Fimg%2Fsubstack_wordmark.png%3Fv%3D2

Linked to: https://ethereumba.substack.com/

**Comment by martintel** [comment]
iframe para agregar:
<iframe src="https://ethereumba.substack.com/embed" width="480" height="320" style="border:1px solid #EEE; background:white;" frameborder="0" scrolling="no"></iframe>

**Comment by martintel** [comment]
We should also add a badge (w/ link) to the Spotify profile of the Podcast. 
Link:
https://open.spotify.com/show/2WPeBSDNqG2YDPGfYHoKPN
Badges: 
[spotify-podcast-badges.zip](https://github.com/ethereumba/EthereumBA-web/files/4674450/spotify-podcast-badges.zip)
