### ISSUE TITLE
Change number of members of the meetup group in the landing page

### ISSUE THREAD

**Issue by martintel** [ethereumba/EthereumBA-web#59]
Now it says 1600+, but we should update it to 1800+

![Screen Shot 2020-06-21 at 18 26 05](https://user-images.githubusercontent.com/447637/85235601-c4956400-b3ec-11ea-9418-2c0dd0855f9c.png)

**Comment by ragonzal** [comment]
Hi guys, let me know when you're about to work this issue.
I can set-up an endpoint to serve this content to the frontend, so it can be updated in the site admin (maybe even get this data from Meetup directly).

For future reference: https://secure.meetup.com/meetup_api/console/?path=/:urlname

**Comment by francopetra** [comment]
Hi @ragonza, great idea! Just looked into Meetup's API and apparently there's an endpoint to get a list of users, but didn't get to find an endpoint with the total count. 
Will change this number manually to solve the issue. If you implement the endpoint let me know and i'll be happy to connect it.

**Comment by ragonzal** [comment]
@francopetra checkout https://api.ethereumba.com/api/v1/meetup-data/
I will update it every hour. And remember, I'm rounding it down so leave the "+" sign
